version: "3.8"
services:

  terraform:
    image: hashicorp/terraform:0.13.4
    entrypoint: "tail -f /dev/null"
    working_dir: /data/codebase
    volumes:
      - .:/data/codebase
    environment:
      - PS1=shell->
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack-full:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
    volumes:
      - "/tmp/localstack:/tmp/localstack"

  test:
    image: ruby:2.7.2-buster
    entrypoint: tail -f /dev/null
    working_dir: /data/codebase
    volumes:
      - .:/data/codebase
    depends_on:
      - terraform
      - localstack

  dockerize:
    image: jwilder/dockerize:0.6.1
    entrypoint: tail -f /dev/null
    depends_on:
      - terraform
      - localstack
